name: Conflict -shared database

on:
  pull_request:
    
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
        DATABASE_URL: ${{ secrets.SHARED_DATABASE_URL }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r neon-project/requirements.txt

      - name: Run migration - delete addresses
        working-directory: neon-project
        run: alembic upgrade b1540c141bb7

      - name: Run migration - add CAP column(expected to fail)
        working-directory: neon-project
        run: |
          set +e
          alembic upgrade d555aff7f21e
          status=$?
          
          if [ $status -eq 0 ]; then
            echo "ERROR: migration succeeded, but it was expected to fail"
            exit 1
          fi
          echo "Migration failed as expected"
          
      - name: Restore database
        working-directory: neon-project
        if: always()
        run: alembic downgrade -1
          
