name: Error in migration - NotNullValues

on:
  pull_request:
    branches: [ "error" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      NEON_API_KEY: ${{ secrets.NEON_API_KEY }}
      NEON_PROJECT_ID: ${{ secrets.NEON_PROJECT_ID }}
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      DATABASE_ROLE: ${{ secrets.DATABASE_ROLE }}

      PR_NUMBER: ${{ github.event.pull_request.number || 'local'}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r neon-project/requirements.txt

      - name: Create Neon branch
        working-directory: neon-project
        run: |
          python  setup_branch.py create

      - name: Run migration (expected to fail)
        run: |
          set +e
          alembic upgrade d7b873c2a0a0
          status=$?
          
          if [ $status -eq 0 ]; then
            echo "ERROR: migration succeeded, but it was expected to fail"
            exit 1
          fi
          echo "Migration failed as expected"
                
      - name: Delete Neon branch
        working-directory: neon-project
        if: always()
        run: |
          python  setup_branch.py cleanup
